:noaudio:
ifdef::revealjs_slideshow[]
[#cover,data-background-image="image/1156524-bg_redhat.png" data-background-color="#cc0000"]
== &nbsp;

[#cover-h1]
GPTE Virtual Training Guide

[#cover-h2]
Tools for VILT

[#cover-logo]
image::{revealjs_cover_image}[]

endif::[]


== Module Topics
:scrollbar:
:data-uri:


* Objectives
* Introduction to Bluejeans
* BlueJeans Client
* Bluejeans Control Panel
* Bluejeans Chat Window
* Instructor or Moderator Interface
* Bluejeans Tools Native Client Addtional Features
* Explaining the learner Interface
* Ending the session



== Objectives
:scrollbar:
:data-uri:

* Utilize the Features of BlueJeans

* Present the Features of BlueJeans to learners


== Introduction to Bluejeans
:scrollbar:
:data-uri:

* Red Hat has selected BlueJeans as our videoconferencing provider for meeting, confrences and VILT.

* BlueJeans has better Voice-Over-IP and video quality over comparable tools
* BlueJeans has very basic system requirements
** Available in the following modes::
      *** Browser plug-in on Google Chrome
      *** Standalone app for Linux, Windows, OS-X operating systems
      *** Mobile app available for iOS and Android
** Consistent UI across multiple devices

== BlueJeans Client
:scrollbar:
:data-uri:

* Bluejeans offers two interfaces to conduct confrences or trainings.
  ** Browser based plugin
  ** Native Client
* Both interfaces are easy to use, with controls located at the top of the screen

* The current speaker is identified via icon and name shown on the screen.

[TIP]
The native clients has better screen sharing and is recommended.

== Bluejeans Control Panel
:scrollbar:
:data-uri:

* The collection of controls are for interactions with the learners and for your own system.

* The control panel allows you to turn your camera and microphone on and off, as well as record your session, or expand your browser window to fill your screen.


[NOTE]
It is not recommended to fill your screen, as it's likely that some learners will have a smaller screen than yours, and you will want to share your browser.


== Bluejeans Control Panel
:scrollbar:
:data-uri:

* The Participants window gives you a list of attendees as well
as some controls for muting all of their lines.

* Share Screen will let you share your view of the VT
environment with learners.

* Settings allows you to fine tune your video and audio settings. Switch
to Phone, if available, gives learners a simple method for connecting to a phone bridge.

[TIP]
Before starting lecture make sure all the learners have muted thier input audio settings.

[WARNING]
Learners have the same interface, including Share Screen. Point out to learners that
they should not share their screen unless requested to do so by you.
 
== Bluejeans Chat Window
:scrollbar:
:data-uri:

* The Chat window allows you to solicit feedback from learners and can also be used as *parking space* for questions in the session.

* The Chat is a good way to interact with learners while not talking when other learners are doing there labs. 

* Be aware of this when asking for responses in chat. The chat interface is also how you can do polling or look for raised hands, as it's your primary non-verbal method for interacting with learners. 

* Private chat is also available in BlueJeans, simply by clicking on the learner's icon in chat, or a chat icon next to the learner's name in the participant
window.

* Have a second screen available with the chat interface open at all times to monitor
the chat room. The second screen might be a separate monitor, or a mobile
application.

[TIP]
Since BlueJeans chats are not saved beyond the session, we recommend the use of *Etherpad* as a place to park your questions and issues, as well as shared interesting documents and links.


== Instructor or Moderator Interface
:scrollbar:
:data-uri:

* There are some items in the interface which are available primarily for the instructor.

* You can mute or unmute everyone.

* Disable entry or exit notification.

* Lock current meeting. This prevents anyone from joining. Beware using
this unless all learners are connected.

== Bluejeans Tools Native Client Addtional Features
:scrollbar:
:data-uri:

* Some Bluejeans tools only available in Native Client:
** On top left of the Bluejeans Native Client click on *APPS*
*** Whiteboard

**** Click to start a new whiteboard session:

**** A blank whiteboard will appear with the toolbar on the left. Post your message.
**** All participants will be able to see the whiteboard. Don't worry, they will NOT be able to see ANY web sites / application windows in your desktop.
**** To stop the session:
**** Click END at the bottom of the toolbar, or
**** Click Stop in the Whiteboard box in the right side menu 

[TIP]
Use a *Digital Pen* for whitebaord.

== Bluejeans Tools Native Client Addtional Features
:scrollbar:
:data-uri:

* Annotation

** Click to Start Annotation, then click the grey bar to start screensharing:
** Meeting participants will then be shown the last screen (web site or app window) you were on prior to the App 2.x window
** With Annotation, you can only share your entire desktop, not a specific application only
** The tool bar will appear on the left. Use the tools to annotate over the screen displayed.
** To stop the annotation, click END at the bottom of the toolbar (or click Stop in the Annotation box in the right side menu). Your screen will continue to be shared to all.
** Go to another webpage or app you want to share, then click the "Annotate" blue bar at top to bring up the toolbar for that page. This blue Annotate bar will also be seen when you are screen sharing, from a Mac.
** To stop screen sharing, click the red bar at the top.
** The floating widget appears while you are screen sharing. Drag it, as needed:
** Click the return arrow at top left to jump back to the app screen
** Click the Camera or Microphone icon to mute (or unmute), or the green screen icon to stop screen sharing
** Hide the participant's video from the top right icon
** Expand the widget window from the lower right corner


== Explaining the learner Interface
:scrollbar:
:data-uri:

* When running a class, start the first day with an explanation of the interface controls. 

* The four key areas are the Settings, Chat, Participants, and reminding learners not to Share Screen unless requested.

* Your first step should be to share your screen. Click the Share Screen icon, and you will be presented with a dialog.

* Share your browser window so you can then step learners through the other features of the interface.

[TIP]
Share your entire desktop. Sharing a single app doesn't zoom the size of the app, it
just places a blue-grey background around it. Of course, be aware that everything on
your desktop will be visible!(Make sure you do not have anything on desktop which you do want learners to see.)


== Ending the session
:scrollbar:
:data-uri:

* At the end of the day, you will want learners to log out.

* Direct them to the Leave icon, then click the Leave button, or have them exit their browser.

* The instructor or moderator can drop everyone from the call when leaving. There's also the option to drop people from the meeting for up to 10 minutes after you leave.

* . Do not leave the meeting running without being there! If learners need to contact you after hours, suggest email or etherpad.